### PR TITLE
Some additions and changes to CatLady's plugins

### PR DESCRIPTION
**Pull request by Cat-Lady**
1. Added Gatling Ammo Fix plugin
2. Fixed descriptions of some plugins (by myself).
3. Grouped some related plugins together on the list.

### CODE REVIEW

**Comment by Cat-Lady** [comment]
Done! Re-sorted plugins alphabetically.

**Comment by Cat-Lady** [comment]
''is it necessary to link to the releases page?''

Actually, I prefer very much to link to "releases" page - I prepare them on purpose, in a way that users can just unpack them straight to plugin's folder without worrying about github structure creating double-folders when downloaded from main repo manually, or messing with git cloning.

Of course, advanced users can sync straight from repo, but for "average" user - that have low chance of finding "Releases" page on its own - I prefer it linked this way.

**Comment by MCOfficer** [comment]
Thinking about it from another angle, the links are supposed to show the "main page" or "landing page", which is not necessarily a README, it can also be a website or forum thread. if you consider your releases page to be the relevant landing page, so be it.

**Comment by Cat-Lady** [comment]
Thanks!

Yea, I consider the "Releases" pages a landing one, for now. The list itself gives short description of each plugin, so "average" user will know what is what, and anyone even a little bit advanced can check the "readme" manually - it is more obviously accessible (via clicking on the repo name) than the semi-hidden "Releases".

**Pull request merged**
